### ISSUE TITLE
As a user looking at a region's profile page, I want to be provided with a quick snapshot of census information for that region so that I can have context of the region's demographic makeup.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/bpo#6]
For each profile, I would want to display the following census information:
- population
- ethnic distribution
- number of subregions
- what else?

And I should be able to select different years.

**Comment by bxharra** [comment]
As a user I'd like to see this a side layer (that I can choose to add and compare it against violence data). 

Would be great to have the following census:
- Number of sub-regions (i don't understand)
- Unemployment rate
- Internet Usage
- Literacy 
- Poverty headcount ratio
- Mortality rate (optional)
- Internal Migration rate
- International migration rate

This is where I based these categories - http://catalog.ihsn.org/index.php/catalog/4376 - they seem to have metadata on that. Otherwise, let me know what we need, and I can try to find the right information for our use. 
-

**Comment by simonfossom** [comment]
Here we should stick to the census information that might correlate to the violate incidents.

Population, religious diversity, unemployment, literacy, poverty makes sense to me.
I'm not sure internet usage, mortality, emigration and internal migration.

**Comment by bxharra** [comment]
sounds good! Agreed. thanks Orzen!

**Comment by simonfossom** [comment]
Great! Thanks for quick reply.
