### ISSUE TITLE
button is just outlined and it should be full color with white text

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/bpo#94]

**Comment by artaabdullahu** [comment]
I think for this button they are thinking. ![button](https://cloud.githubusercontent.com/assets/21961919/21389815/d49247be-c783-11e6-916f-45e741213e3f.png)

**Comment by artaabdullahu** [comment]
@partini hover should be white instead of #FFA400.

**Comment by partini** [comment]
WHITE SPACE WHERE?

On Wed, Dec 28, 2016, 10:57 Arta <notifications@github.com> wrote:

@partini <https://github.com/partini> hover should be white instead of
#FFA400.

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/opendatakosovo/bpo/issues/94#issuecomment-269454320>,
or mute the thread

**Comment by artaabdullahu** [comment]
@partini qishtu po mendoj qe duhet me qene ngjyra ndryshe.
![here](https://cloud.githubusercontent.com/assets/21961919/21520184/d33405e6-ccf2-11e6-996b-6475954136a4.png)
